### ISSUE TITLE
unique IDs for CRUD changes?

### ISSUE THREAD

**Issue by pascalpp** [StayWokeOrg/central#6]
I think it would be useful if each record had some unique ID, so we can make PUT/PATCH/DELETE requests to /api/contacts/:id (which I believe is REST convention) in order to rewrite, modify, or delete a record. The initial POST to /api/contacts should return this ID in the response so the client knows which record they created. Not sure what the ID should be: the email, or the phone number, or just an incremental integer? latter would probably be simpler, but then we'd need an API for doing ID lookups.

**Comment by mattstauffer** [comment]
We can use incremental ID that each already has. What would we need lookup by/for?

**Comment by pascalpp** [comment]
Just thinking ahead when we have returning users who might want to modify their info, or remove it. Not critical for near term.

**Comment by mattstauffer** [comment]
Cool. Added the ID to the return for now and we can add other endpoints as we need them.
